import ConsistentHistories.Foundation.Cut.Structure

/-!
Paper section 3.3: Consistency models for located semilattices with Cut.

-/

namespace ConsistentHistories.Models.Cut.Consistency

open ConsistentHistories.Foundation.Cut.Structure
open ConsistentHistories.Foundation.Cut.Flags
open ConsistentHistories.Foundation.LocatedSemilattices.Basic
open ConsistentHistories.Foundation.LocatedSemilattices.Basic.LocatedSemilattice
open ConsistentHistories.Foundation.Cut.Structure.LocatedSemilatticeWithCut

universe u v

/-!
Concrete one-controller model used in the proof of Proposition 3.3.1.
-/

/-- Proposition 3.3.1: the single controller `*`. -/
abbrev ConcreteCtrl : Type := PUnit

/--
Proposition 3.3.1: the concrete times
`{top, bot} ∪ ⋃ i, {ni_i, cm_i, cu_i}`.
-/
inductive ConcreteTime where
  | bot
  | top
  | nextIndex (i : Nat)
  | cutMe (i : Nat)
  | cutYou (i : Nat)
  deriving DecidableEq

namespace ConcreteTime

/-- The time label corresponding to a cutting flag symbol and index. -/
def ofFlagKind : CutFlagKind → Nat → ConcreteTime
  | CutFlagKind.nextIndex, i => nextIndex i
  | CutFlagKind.cutMe, i => cutMe i
  | CutFlagKind.cutYou, i => cutYou i

/--
Proposition 3.3.1: flag action in the concrete consistency model.

Flags send `bot` to their own concrete label and every other time to `top`.
-/
def flagApply (kind : CutFlagKind) (i : Nat) : ConcreteTime → ConcreteTime
  | bot => ofFlagKind kind i
  | _ => top

theorem flagApply_bot (kind : CutFlagKind) (i : Nat) :
    flagApply kind i bot = ofFlagKind kind i :=
  rfl

theorem flagApply_of_ne_bot
    (kind : CutFlagKind) (i : Nat) {t : ConcreteTime} (h : t ≠ bot) :
    flagApply kind i t = top := by
  cases t with
  | bot => exact False.elim (h rfl)
  | top => rfl
  | nextIndex n => rfl
  | cutMe n => rfl
  | cutYou n => rfl

theorem flagApply_top (kind : CutFlagKind) (i : Nat) :
    flagApply kind i top = top :=
  rfl

theorem flagApply_ofFlagKind (kind kind' : CutFlagKind) (i j : Nat) :
    flagApply kind i (ofFlagKind kind' j) = top := by
  cases kind' <;> rfl

theorem ofFlagKind_injective {kind kind' : CutFlagKind} {i j : Nat}
    (h : ofFlagKind kind i = ofFlagKind kind' j) : kind = kind' ∧ i = j := by
  cases kind <;> cases kind' <;> simp [ofFlagKind] at h ⊢ <;> simp_all

/-- Rank along the main `ni/cu` chain, ordered by reverse rank. -/
def chainRank? : ConcreteTime → Option Nat
  | nextIndex i => some (2 * i + 1)
  | cutYou i => some (2 * i)
  | _ => none

/-- The index of a `cm` leaf, when present. -/
def cutMeIndex? : ConcreteTime → Option Nat
  | cutMe i => some i
  | _ => none

/--
Proposition 3.3.1(4): a closed-form version of the order generated by the clause's
inequalities.

Higher chain rank is lower in the order. The `cm_j` leaf sits above `ni_j`,
which means all chain elements below `ni_j` are also below `cm_j`.
-/
def le (x y : ConcreteTime) : Prop :=
  x = bot ∨ y = top ∨ x = y ∨
    match chainRank? x, chainRank? y, cutMeIndex? y with
    | some rx, some ry, _ => ry <= rx
    | some rx, none, some j => 2 * j + 1 <= rx
    | _, _, _ => False

theorem bot_le (t : ConcreteTime) : le bot t := by
  exact Or.inl rfl

theorem le_top (t : ConcreteTime) : le t top := by
  exact Or.inr (Or.inl rfl)

theorem le_refl (t : ConcreteTime) : le t t := by
  exact Or.inr (Or.inr (Or.inl rfl))

theorem next_le_cutMe (j : Nat) : le (nextIndex j) (cutMe j) := by
  simp [le, chainRank?, cutMeIndex?]

theorem next_le_cutYou (j : Nat) : le (nextIndex j) (cutYou j) := by
  simp [le, chainRank?, cutMeIndex?]

theorem cutYou_le_next {i j : Nat} (hij : i < j) : le (cutYou j) (nextIndex i) := by
  simp [le, chainRank?, cutMeIndex?]
  have hsucc : i + 1 <= j := Nat.succ_le_of_lt hij
  omega

/-- Select the upper of two chain elements. Both inputs must be chain elements. -/
def joinChain (x y : ConcreteTime) : ConcreteTime :=
  match chainRank? x, chainRank? y with
  | some rx, some ry => if rx <= ry then x else y
  | _, _ => top

/-- Join a chain element with a `cm` leaf. -/
def joinChainCutMe (chain : ConcreteTime) (j : Nat) : ConcreteTime :=
  match chainRank? chain with
  | some r => if 2 * j + 1 <= r then cutMe j else top
  | none => top

/--
Proposition 3.3.1: concrete join operation used as attestation in the
one-controller consistency model.
-/
def join : ConcreteTime → ConcreteTime → ConcreteTime
  | bot, t => t
  | t, bot => t
  | top, _ => top
  | _, top => top
  | cutMe i, cutMe j => if i = j then cutMe i else top
  | cutMe j, t => joinChainCutMe t j
  | t, cutMe j => joinChainCutMe t j
  | t, u => joinChain t u

theorem join_bot_left (t : ConcreteTime) : join bot t = t := by
  cases t <;> rfl

theorem join_bot_right (t : ConcreteTime) : join t bot = t := by
  cases t <;> rfl

theorem join_top_left (t : ConcreteTime) : join top t = top := by
  cases t <;> rfl

theorem join_top_right (t : ConcreteTime) : join t top = top := by
  cases t <;> rfl

/-- Proposition 3.3.1: same-index concrete `cutMe` and `cutYou` branches join to top. -/
theorem cutMe_join_cutYou_same (j : Nat) :
    join (cutMe j) (cutYou j) = top := by
  simp [join, joinChainCutMe, chainRank?]

theorem join_idem (t : ConcreteTime) : join t t = t := by
  cases t <;> simp [join, joinChain, chainRank?]

theorem join_comm (t u : ConcreteTime) : join t u = join u t := by
  cases t <;> cases u <;> simp [join, joinChain, joinChainCutMe, chainRank?]
  · rename_i i j
    by_cases h : 2 * i <= 2 * j
    · simp [h]
      by_cases h' : 2 * j <= 2 * i
      · have hij : i = j := by omega
        simp [hij]
      · omega
    · simp [h]
      have h' : 2 * j <= 2 * i := by omega
      omega
  · rename_i i j
    by_cases h : 2 * i + 1 <= 2 * j
    · simp [h]
      have h' : ¬ 2 * j <= 2 * i + 1 := by omega
      omega
    · simp [h]
      have h' : 2 * j <= 2 * i + 1 := by omega
      omega
  · rename_i i j
    by_cases h : i = j
    · simp [h]
    · simp [h]
      have h' : ¬ j = i := by intro hji; exact h hji.symm
      simp [h']
  · rename_i i j
    by_cases h : 2 * i <= 2 * j + 1
    · simp [h]
      have h' : ¬ 2 * j + 1 <= 2 * i := by omega
      omega
    · simp [h]
      have h' : 2 * j + 1 <= 2 * i := by omega
      omega
  · rename_i i j
    by_cases h : 2 * i <= 2 * j
    · simp [h]
      by_cases h' : 2 * j <= 2 * i
      · have hij : i = j := by omega
        simp [hij]
      · omega
    · simp [h]
      have h' : 2 * j <= 2 * i := by omega
      omega

theorem le_antisymm {t u : ConcreteTime} (htu : le t u) (hut : le u t) : t = u := by
  cases t <;> cases u <;> simp [le, chainRank?, cutMeIndex?] at htu hut ⊢ <;> omega

theorem le_trans {t u v : ConcreteTime} (htu : le t u) (huv : le u v) : le t v := by
  cases t <;> cases u <;> cases v <;>
    simp [le, chainRank?, cutMeIndex?] at htu huv ⊢ <;>
    omega

theorem le_join_left (t u : ConcreteTime) : le t (join t u) := by
  cases t <;> cases u <;>
    simp [le, join, joinChain, joinChainCutMe, chainRank?, cutMeIndex?]
  all_goals repeat split
  all_goals try simp_all
  all_goals omega

theorem le_join_right (t u : ConcreteTime) : le u (join t u) := by
  rw [join_comm]
  exact le_join_left u t

theorem join_le_of_le {t u v : ConcreteTime}
    (htv : le t v) (huv : le u v) : le (join t u) v := by
  cases t <;> cases u <;> cases v <;>
    simp [le, join, joinChain, joinChainCutMe, chainRank?, cutMeIndex?] at htv huv ⊢
  all_goals repeat split
  all_goals try simp_all
  all_goals omega

theorem join_assoc (t u v : ConcreteTime) : join (join t u) v = join t (join u v) := by
  apply le_antisymm
  · apply join_le_of_le
    · apply join_le_of_le
      · exact le_join_left t (join u v)
      · exact le_trans (le_join_left u v) (le_join_right t (join u v))
    · exact le_trans (le_join_right u v) (le_join_right t (join u v))
  · apply join_le_of_le
    · exact le_trans (le_join_left t u) (le_join_left (join t u) v)
    · apply join_le_of_le
      · exact le_trans (le_join_right t u) (le_join_left (join t u) v)
      · exact le_join_right (join t u) v

theorem join_preserves_top_join {t t' s s' : ConcreteTime}
    (hss' : join s s' = top) : join (join t s) (join t' s') = top := by
  let J := join (join t s) (join t' s')
  have hsJ : le s J :=
    le_trans (le_join_right t s) (le_join_left (join t s) (join t' s'))
  have hs'J : le s' J :=
    le_trans (le_join_right t' s') (le_join_right (join t s) (join t' s'))
  have htopJ : le top J := by
    simpa [J, hss'] using join_le_of_le hsJ hs'J
  exact le_antisymm (le_top J) htopJ

end ConcreteTime

/-- Proposition 3.3.1: the concrete one-controller located semilattice. -/
instance concreteLocatedSemilattice : LocatedSemilattice ConcreteTime ConcreteCtrl where
  attest := ConcreteTime.join
  controller := fun _ => PUnit.unit
  bot := fun _ => ConcreteTime.bot
  top := fun _ => ConcreteTime.top
  bot_controller := by intro p; rfl
  top_controller := by intro p; rfl
  controller_preserving := by intro t s; rfl
  self_join_idem := by intro t; exact ConcreteTime.join_idem t
  self_join_comm := by intro t t' _h; exact ConcreteTime.join_comm t t'
  self_join_assoc := by intro t t' u _h _h'; exact ConcreteTime.join_assoc t t' u
  self_bot_le := by intro _p t _h; exact ConcreteTime.join_bot_left t
  self_le_top := by intro _p t _h; exact ConcreteTime.join_top_right t
  expansive := by
    intro t s
    calc
      ConcreteTime.join (ConcreteTime.join t s) t =
          ConcreteTime.join t (ConcreteTime.join s t) :=
        ConcreteTime.join_assoc t s t
      _ = ConcreteTime.join t (ConcreteTime.join t s) := by
        rw [ConcreteTime.join_comm s t]
      _ = ConcreteTime.join (ConcreteTime.join t t) s :=
        (ConcreteTime.join_assoc t t s).symm
      _ = ConcreteTime.join t s := by rw [ConcreteTime.join_idem]
  contradiction_preserving := by
    intro _t _t' _s _s' _htt' _hss' hcontr
    constructor
    · rfl
    · exact ConcreteTime.join_preserves_top_join hcontr.2

/-- Proposition 3.3.1: concrete attestation is controller-preserving. -/
theorem concreteLocatedSemilattice_controller_preserving
    (t s : ConcreteTime) :
    concreteLocatedSemilattice.controller (ConcreteTime.join t s) =
      concreteLocatedSemilattice.controller t :=
  concreteLocatedSemilattice.controller_preserving t s

/-- Proposition 3.3.1: concrete attestation is expansive. -/
theorem concreteLocatedSemilattice_expansive
    (t s : ConcreteTime) :
    t ≼ (ConcreteTime.join t s) :=
  concreteLocatedSemilattice.le_attest t s

/-- Proposition 3.3.1: concrete attestation preserves contradiction. -/
theorem concreteLocatedSemilattice_contradiction_preserving
    {t t' s s' : ConcreteTime}
    (hcontr : s 🗲 s') :
    (ConcreteTime.join t s) 🗲 (ConcreteTime.join t' s') :=
  ⟨rfl, ConcreteTime.join_preserves_top_join hcontr.2⟩

/-- Proposition 3.3.1: same-index concrete `cutMe` and `cutYou` branches contradict. -/
theorem concreteLocatedSemilattice_cutMe_contradicts_cutYou (j : Nat) :
    (ConcreteTime.cutMe j) 🗲 (ConcreteTime.cutYou j) := by
  constructor
  · rfl
  · exact ConcreteTime.cutMe_join_cutYou_same j

/-- Proposition 3.3.1: the concrete located order is the closed-form concrete order. -/
theorem concreteLocatedSemilattice_le_iff_concreteTime_le
    (t u : ConcreteTime) :
    t ≼ u ↔ ConcreteTime.le t u := by
  constructor
  · intro hle
    have hjoin : ConcreteTime.join t u = u := hle.2
    simpa [hjoin] using ConcreteTime.le_join_left t u
  · intro hle
    constructor
    · rfl
    · exact ConcreteTime.le_antisymm
        (ConcreteTime.join_le_of_le hle (ConcreteTime.le_refl u))
        (ConcreteTime.le_join_right t u)

/-- Proposition 3.3.1: concrete located strict order is strict closed-form order. -/
theorem concreteLocatedSemilattice_lt_iff_concreteTime_lt
    (t u : ConcreteTime) :
    t ≺ u ↔ ConcreteTime.le t u ∧ t ≠ u := by
  constructor
  · intro hlt
    exact ⟨(concreteLocatedSemilattice_le_iff_concreteTime_le t u).mp hlt.1, hlt.2⟩
  · intro hlt
    exact ⟨(concreteLocatedSemilattice_le_iff_concreteTime_le t u).mpr hlt.1, hlt.2⟩

/-- Proposition 3.3.1: concrete bottom is below every concrete time. -/
theorem concreteLocatedSemilattice_bot_le (t : ConcreteTime) :
    ConcreteTime.bot ≼ t := by
  exact (concreteLocatedSemilattice_le_iff_concreteTime_le ConcreteTime.bot t).mpr
    (ConcreteTime.bot_le t)

/-- Proposition 3.3.1: every concrete time is below concrete top. -/
theorem concreteLocatedSemilattice_le_top (t : ConcreteTime) :
    t ≼ ConcreteTime.top := by
  exact (concreteLocatedSemilattice_le_iff_concreteTime_le t ConcreteTime.top).mpr
    (ConcreteTime.le_top t)

/-- Proposition 3.3.1: `ni_j` is below `cm_j` in the concrete consistency model. -/
theorem concreteLocatedSemilattice_next_le_cutMe (j : Nat) :
    (ConcreteTime.nextIndex j) ≼ (ConcreteTime.cutMe j) := by
  exact
    (concreteLocatedSemilattice_le_iff_concreteTime_le
      (ConcreteTime.nextIndex j) (ConcreteTime.cutMe j)).mpr
      (ConcreteTime.next_le_cutMe j)

/-- Proposition 3.3.1: `ni_j` is below `cu_j` in the concrete consistency model. -/
theorem concreteLocatedSemilattice_next_le_cutYou (j : Nat) :
    (ConcreteTime.nextIndex j) ≼ (ConcreteTime.cutYou j) := by
  exact
    (concreteLocatedSemilattice_le_iff_concreteTime_le
      (ConcreteTime.nextIndex j) (ConcreteTime.cutYou j)).mpr
      (ConcreteTime.next_le_cutYou j)

/-- Proposition 3.3.1: `cu_j` is below `ni_i` whenever `i < j`. -/
theorem concreteLocatedSemilattice_cutYou_le_next {i j : Nat} (hij : i < j) :
    (ConcreteTime.cutYou j) ≼ (ConcreteTime.nextIndex i) := by
  exact
    (concreteLocatedSemilattice_le_iff_concreteTime_le
      (ConcreteTime.cutYou j) (ConcreteTime.nextIndex i)).mpr
      (ConcreteTime.cutYou_le_next hij)

/-- Proposition 3.3.1: concrete cutting flag. -/
def concreteFlag (kind : CutFlagKind) (i : Nat) : Flag ConcreteTime where
  toFun := ConcreteTime.flagApply kind i
  controller_preserving := by intro _t; rfl
  expansive := by
    intro t
    constructor
    · rfl
    · cases t <;> simp [concreteLocatedSemilattice, ConcreteTime.flagApply,
        ConcreteTime.ofFlagKind, ConcreteTime.join]

/-- Proposition 3.3.1: a bundled concrete flag sends bottom to its own label. -/
theorem concreteFlag_apply_bot (kind : CutFlagKind) (i : Nat) :
    concreteFlag kind i ConcreteTime.bot = ConcreteTime.ofFlagKind kind i :=
  rfl

/-- Proposition 3.3.1: a bundled concrete flag sends every non-bottom input to top. -/
theorem concreteFlag_apply_of_ne_bot
    (kind : CutFlagKind) (i : Nat) {t : ConcreteTime}
    (h : t ≠ ConcreteTime.bot) :
    concreteFlag kind i t = ConcreteTime.top :=
  ConcreteTime.flagApply_of_ne_bot kind i h

/-- Proposition 3.3.1: concrete flag application is expansive. -/
theorem concreteFlag_expansive
    (kind : CutFlagKind) (i : Nat) (t : ConcreteTime) :
    t ≼ (concreteFlag kind i t) :=
  (concreteFlag kind i).expansive t

/--
Proposition 3.3.1: a concrete flag application is consistent exactly on bottom
input.
-/
theorem concreteFlag_apply_consistent_iff_bot
    (kind : CutFlagKind) (i : Nat) (t : ConcreteTime) :
    concreteLocatedSemilattice.ConsistentTime (concreteFlag kind i t) ↔
      t = ConcreteTime.bot := by
  constructor
  · intro h
    cases t <;>
      simp [concreteLocatedSemilattice, LocatedSemilattice.ConsistentTime,
        concreteFlag, ConcreteTime.flagApply] at h ⊢
  · intro ht
    rw [ht]
    cases kind <;>
      simp [concreteLocatedSemilattice, LocatedSemilattice.ConsistentTime,
        concreteFlag, ConcreteTime.flagApply, ConcreteTime.ofFlagKind]

theorem concreteFlag_injective {kind kind' : CutFlagKind} {i j : Nat}
    (h : concreteFlag kind i = concreteFlag kind' j) : kind = kind' ∧ i = j := by
  have happly :=
    congrArg (fun Q : Flag ConcreteTime => Q ConcreteTime.bot) h
  exact ConcreteTime.ofFlagKind_injective
    (by simpa [concreteFlag, ConcreteTime.flagApply] using happly)

/--
Proposition 3.3.1: if two concrete flag applications are equal and the common
value is consistent, then both inputs were bottom and the flag labels agree.
-/
theorem concreteFlag_eq_consistent_inputs_bot_and_symbol_eq
    {kind kind' : CutFlagKind} {i j : Nat} {t t' : ConcreteTime}
    (hcons : concreteLocatedSemilattice.ConsistentTime (concreteFlag kind i t))
    (heq : concreteFlag kind i t = concreteFlag kind' j t') :
    t = ConcreteTime.bot ∧ t' = ConcreteTime.bot ∧ kind = kind' ∧ i = j := by
  have ht : t = ConcreteTime.bot :=
    (concreteFlag_apply_consistent_iff_bot kind i t).mp hcons
  have hcons' :
      concreteLocatedSemilattice.ConsistentTime (concreteFlag kind' j t') := by
    rw [← heq]
    exact hcons
  have ht' : t' = ConcreteTime.bot :=
    (concreteFlag_apply_consistent_iff_bot kind' j t').mp hcons'
  have hlabel : ConcreteTime.ofFlagKind kind i = ConcreteTime.ofFlagKind kind' j := by
    rw [ht, ht'] at heq
    simpa [concreteFlag, ConcreteTime.flagApply] using heq
  rcases ConcreteTime.ofFlagKind_injective hlabel with ⟨hkind, hi⟩
  exact ⟨ht, ht', hkind, hi⟩

/--
In the concrete consistency model, the source-center shape required by the Cut rule is
never a consistent time. The outer `cutMe` flag is consistent only on bottom input, but its
displayed input already contains a `cutYou` flag application.
-/
theorem concreteFlag_cut_source_center_inconsistent
    (lower center : Nat) (tj tk : ConcreteTime) :
    ¬ concreteLocatedSemilattice.ConsistentTime
      (concreteFlag CutFlagKind.cutMe lower
        (tj # (concreteFlag CutFlagKind.cutYou center tk))) := by
  intro hconsistent
  have hbase :
      tj # (concreteFlag CutFlagKind.cutYou center tk) = ConcreteTime.bot :=
    (concreteFlag_apply_consistent_iff_bot CutFlagKind.cutMe lower _).mp hconsistent
  cases tj <;> cases tk <;>
    simp [concreteLocatedSemilattice, concreteFlag, ConcreteTime.flagApply,
      ConcreteTime.ofFlagKind, ConcreteTime.join, ConcreteTime.joinChain,
      ConcreteTime.joinChainCutMe, ConcreteTime.chainRank?] at hbase
  all_goals
    repeat split at hbase
    all_goals cases hbase

/--
The concrete consistency model has no nontrivial strict growth between consistent outputs
of the same cutting flag. Any consistent concrete flag output came from `bot`, so two
consistent same-flag outputs are equal.
-/
theorem concreteFlag_no_consistent_same_flag_strict_growth
    (kind : CutFlagKind) (i : Nat) {t t' : ConcreteTime}
    (hcons : concreteLocatedSemilattice.ConsistentTime (concreteFlag kind i t))
    (hcons' : concreteLocatedSemilattice.ConsistentTime (concreteFlag kind i t')) :
    ¬ (concreteFlag kind i t) ≺ (concreteFlag kind i t') := by
  intro hlt
  have ht : t = ConcreteTime.bot :=
    (concreteFlag_apply_consistent_iff_bot kind i t).mp hcons
  have ht' : t' = ConcreteTime.bot :=
    (concreteFlag_apply_consistent_iff_bot kind i t').mp hcons'
  exact hlt.2 (by rw [ht, ht'])

/-- Proposition 3.3.1: the concrete cutting flag-set. -/
def concreteCuttingFlagSet : FlagSet ConcreteTime where
  member Q := ∃ kind i, Q = concreteFlag kind i
  injective_where_consistent := by
    intro Q Q' t t' hmem hmem' hcons heq
    rcases hmem with ⟨kind, i, rfl⟩
    rcases hmem' with ⟨kind', j, rfl⟩
    have hlabel : ConcreteTime.ofFlagKind kind i = ConcreteTime.ofFlagKind kind' j := by
      cases t <;> cases t' <;>
        simp [concreteFlag, concreteLocatedSemilattice, LocatedSemilattice.ConsistentTime,
          ConcreteTime.flagApply, ConcreteTime.ofFlagKind] at hcons heq ⊢
      · exact heq
      all_goals exact False.elim (hcons heq)
    rcases ConcreteTime.ofFlagKind_injective hlabel with ⟨hkind, hi⟩
    subst hkind
    subst hi
    rfl

/-- Proposition 3.3.1: every concrete cutting symbol belongs to the concrete flag-set. -/
theorem concreteCuttingFlagSet_member_concreteFlag
    (kind : CutFlagKind) (i : Nat) :
    concreteCuttingFlagSet.member (concreteFlag kind i) :=
  ⟨kind, i, rfl⟩

/-- Proposition 3.3.1: the concrete located semilattice with Cut. -/
def concreteLocatedSemilatticeWithCut : LocatedSemilatticeWithCut ConcreteTime ConcreteCtrl where
  toLocatedSemilattice := concreteLocatedSemilattice
  cuttingFlagSet := concreteCuttingFlagSet
  cutting := concreteFlag
  cutting_mem := by
    intro kind i
    exact ⟨kind, i, rfl⟩
  cutting_mem_complete := by
    intro Q hmem
    exact hmem
  next_le_cutme := by
    intro j t
    constructor
    · rfl
    · cases t <;>
        simp [concreteLocatedSemilattice, concreteFlag, ConcreteTime.flagApply,
          ConcreteTime.ofFlagKind, ConcreteTime.join, ConcreteTime.joinChainCutMe,
          ConcreteTime.chainRank?]
  next_le_cutyou := by
    intro j t
    constructor
    · rfl
    · cases t <;>
        simp [concreteLocatedSemilattice, concreteFlag, ConcreteTime.flagApply,
          ConcreteTime.ofFlagKind, ConcreteTime.join, ConcreteTime.joinChain,
          ConcreteTime.chainRank?]
  cutyou_le_next := by
    intro i j hij t
    constructor
    · rfl
    · cases t <;>
        simp [concreteLocatedSemilattice, concreteFlag, ConcreteTime.flagApply,
          ConcreteTime.ofFlagKind, ConcreteTime.join, ConcreteTime.joinChain,
          ConcreteTime.chainRank?]
      omega
  cutme_contradicts_cutyou := by
    intro j t t' _hctrl
    constructor
    · rfl
    · cases t <;> cases t' <;>
        simp [concreteLocatedSemilattice, concreteFlag, ConcreteTime.flagApply,
          ConcreteTime.ofFlagKind, ConcreteTime.join, ConcreteTime.joinChainCutMe,
          ConcreteTime.chainRank?]
  cutting_injective := by
    intro _kind _kind' _i _i' h
    exact concreteFlag_injective h

/-- Proposition 3.3.1: a located semilattice with Cut exists. -/
theorem locatedSemilatticeWithCut_exists :
    ∃ (Time Ctrl : Type), Nonempty (LocatedSemilatticeWithCut Time Ctrl) :=
  ⟨ConcreteTime, ConcreteCtrl, ⟨concreteLocatedSemilatticeWithCut⟩⟩

/-- Proposition 3.3.1: the concrete consistency model is sequential. -/
theorem concreteLocatedSemilattice_sequential :
    concreteLocatedSemilattice.Sequential := by
  intro p t t'
  rcases t with ⟨t, _ht⟩
  rcases t' with ⟨t', _ht'⟩
  cases t <;> cases t' <;>
    simp [LocatedSemilattice.fiber, concreteLocatedSemilattice, ConcreteTime.join,
      ConcreteTime.joinChain, ConcreteTime.joinChainCutMe, ConcreteTime.chainRank?]
  all_goals repeat split
  all_goals simp_all
  all_goals omega

/--
Proposition 3.3.1: the unique concrete controller fiber has the top-tree
incomparable-join-top property.
-/
theorem concreteLocatedSemilattice_incomparable_join_top
    {t t' : timeAt (Time := ConcreteTime) PUnit.unit}
    (hinc :
      (concreteLocatedSemilattice.fiber PUnit.unit).Incomparable t t') :
    (concreteLocatedSemilattice.fiber PUnit.unit).join t t' =
      (concreteLocatedSemilattice.fiber PUnit.unit).top := by
  exact (concreteLocatedSemilattice.fiber PUnit.unit).incomparable_join_top_of_sequential
    (concreteLocatedSemilattice_sequential PUnit.unit) hinc

/-- Proposition 3.3.1: a sequential located semilattice with Cut exists. -/
theorem sequential_locatedSemilatticeWithCut_exists :
    ∃ (Time Ctrl : Type), Nonempty (SequentialLocatedSemilatticeWithCut Time Ctrl) :=
  ⟨ConcreteTime, ConcreteCtrl,
    ⟨{ toLocatedSemilatticeWithCut := concreteLocatedSemilatticeWithCut
       sequential := concreteLocatedSemilattice_sequential }⟩⟩

/--
Definition 3.3.2: located semilattice part of the
countably many-controller product construction.
-/
def manyLocatedSemilattice
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) : LocatedSemilattice (Nat × Time) Nat where
  attest := fun t s => (t.1, t.2 # s.2)
  controller := Prod.fst
  bot := fun p => (p, bot base)
  top := fun p => (p, top base)
  bot_controller := by intro _p; rfl
  top_controller := by intro _p; rfl
  controller_preserving := by intro _t _s; rfl
  self_join_idem := by
    intro t
    cases t
    simp [self_join_idem]
  self_join_comm := by
    intro t t' hctrl
    cases t with
    | mk p x =>
      cases t' with
      | mk p' y =>
        dsimp at hctrl ⊢
        cases hctrl
        simp [self_join_comm ((hbase x).trans (hbase y).symm)]
  self_join_assoc := by
    intro t t' r _htt' _ht'r
    cases t with
    | mk _p x =>
      cases t' with
      | mk _p' y =>
        cases r with
        | mk _p'' z =>
          simp [self_join_assoc
            ((hbase x).trans (hbase y).symm)
            ((hbase y).trans (hbase z).symm)]
  self_bot_le := by
    intro p t hctrl
    cases t with
    | mk p' x =>
      dsimp at hctrl ⊢
      cases hctrl
      simp [self_bot_le base x (hbase x)]
  self_le_top := by
    intro p t hctrl
    cases t with
    | mk p' x =>
      dsimp at hctrl ⊢
      cases hctrl
      simp [self_le_top base x (hbase x)]
  expansive := by
    intro t s
    cases t with
    | mk _p x =>
      cases s with
      | mk _p' y =>
        simp [expansive x y]
  contradiction_preserving := by
    intro t t' s s' htt' hss' hcontr
    cases t with
    | mk _p x =>
      cases t' with
      | mk _p' x' =>
        cases s with
        | mk _q y =>
          cases s' with
          | mk _q' y' =>
            dsimp at htt' hss' hcontr ⊢
            constructor
            · exact htt'
            · cases htt'
              cases hss'
              rcases hcontr with ⟨_hctrl, hjoin⟩
              have hraw : RawContradicts controller attest top y y' := by
                constructor
                · exact (hbase y).trans (hbase y').symm
                · simpa [hbase y] using hjoin
              have hout := contradiction_preserving
                ((hbase x).trans (hbase x').symm)
                ((hbase y).trans (hbase y').symm)
                hraw
              simpa [RawContradicts, hbase (x # y)] using hout.2

/-- Definition 3.3.2: product bottom time. -/
theorem manyLocatedSemilattice_bot_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) :
    (manyLocatedSemilattice base hbase).bot p = (p, bot base) :=
  rfl

/-- Definition 3.3.2: product top time. -/
theorem manyLocatedSemilattice_top_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) :
    (manyLocatedSemilattice base hbase).top p = (p, top base) :=
  rfl

/-- Definition 3.3.2: product attestation. -/
theorem manyLocatedSemilattice_attest_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p p' : Nat) (t t' : Time) :
    (manyLocatedSemilattice base hbase).attest (p, t) (p', t') =
      (p, t # t') :=
  rfl

/-- Definition 3.3.2: product attestation keeps the left product controller. -/
theorem manyLocatedSemilattice_attest_fst
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p p' : Nat) (t t' : Time) :
    ((manyLocatedSemilattice base hbase).attest (p, t) (p', t')).1 = p :=
  rfl

/-- Definition 3.3.2: product attestation applies base attestation to base times. -/
theorem manyLocatedSemilattice_attest_snd
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p p' : Nat) (t t' : Time) :
    ((manyLocatedSemilattice base hbase).attest (p, t) (p', t')).2 =
      t # t' :=
  rfl

/-- Definition 3.3.2: product controller projection. -/
theorem manyLocatedSemilattice_controller_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p : Nat) (t : Time) :
    (manyLocatedSemilattice base hbase).controller (p, t) = p :=
  rfl

/--
Definition 3.3.2: each product controller fiber has the same order as the
one-controller base model.
-/
theorem manyLocatedSemilattice_same_controller_le_iff_base_le
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyLocatedSemilattice base hbase).le (p, t) (p, t') ↔ t ≼ t' := by
  constructor
  · intro hle
    constructor
    · exact (hbase t).trans (hbase t').symm
    · exact congrArg Prod.snd hle.2
  · intro hle
    constructor
    · rfl
    · exact Prod.ext rfl hle.2

/--
Definition 3.3.2: the strict order in a product controller fiber is the base
strict order.
-/
theorem manyLocatedSemilattice_same_controller_lt_iff_base_lt
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyLocatedSemilattice base hbase).lt (p, t) (p, t') ↔ t ≺ t' := by
  constructor
  · intro hlt
    exact ⟨(manyLocatedSemilattice_same_controller_le_iff_base_le base hbase p t t').mp
        hlt.1, by
      intro ht
      exact hlt.2 (Prod.ext rfl ht)⟩
  · intro hlt
    exact ⟨(manyLocatedSemilattice_same_controller_le_iff_base_le base hbase p t t').mpr
        hlt.1, by
      intro ht
      exact hlt.2 (congrArg Prod.snd ht)⟩

/--
Definition 3.3.2: contradiction in a product controller fiber is exactly
contradiction in the one-controller base model.
-/
theorem manyLocatedSemilattice_same_controller_contradicts_iff_base_contradicts
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyLocatedSemilattice base hbase).Contradicts (p, t) (p, t') ↔
      t 🗲 t' := by
  constructor
  · intro hcontr
    constructor
    · exact (hbase t).trans (hbase t').symm
    · have hjoinBase : t # t' = top base :=
        congrArg Prod.snd hcontr.2
      simpa [hbase t] using hjoinBase
  · intro hcontr
    constructor
    · rfl
    · have hjoinBase : t # t' = top base := by
        simpa [hbase t] using hcontr.2
      exact Prod.ext rfl hjoinBase

/-- Sequentiality transfers from the base model to the many-controller product. -/
theorem manyLocatedSemilattice_sequential
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (hseq : Sequential (Time := Time)) :
    (manyLocatedSemilattice base hbase).Sequential := by
  intro p t t'
  rcases t with ⟨⟨p0, x⟩, ht⟩
  rcases t' with ⟨⟨p1, y⟩, ht'⟩
  dsimp [manyLocatedSemilattice] at ht ht'
  subst p0
  subst p1
  rcases hseq base ⟨x, hbase x⟩ ⟨y, hbase y⟩ with hleft | hright | htop
  · left
    apply Subtype.ext
    exact Prod.ext rfl (congrArg Subtype.val hleft)
  · right
    left
    apply Subtype.ext
    exact Prod.ext rfl (congrArg Subtype.val hright)
  · right
    right
    apply Subtype.ext
    exact Prod.ext rfl (congrArg Subtype.val htop)

/-- Definition 3.3.2: lift a base flag pointwise. -/
def manyFlag
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (Q : Flag Time) :
    @Flag (Nat × Time) Nat (manyLocatedSemilattice base hbase) :=
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  { toFun := fun t => (t.1, Q t.2)
    controller_preserving := by intro _t; rfl
    expansive := by
      intro t
      cases t with
      | mk p x =>
        constructor
        · rfl
        · exact congrArg (fun z => (p, z)) (Q.expansive x).2 }

/-- Definition 3.3.2: product flag application. -/
theorem manyFlag_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (Q : Flag Time) (p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyFlag base hbase Q).toFun (p, t) = (p, Q t) :=
  rfl

/-- Definition 3.3.2: product flags preserve the product controller. -/
theorem manyFlag_controller_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (Q : Flag Time)
    (p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyLocatedSemilattice base hbase).controller
      ((manyFlag base hbase Q).toFun (p, t)) = p :=
  rfl

/-- Definition 3.3.2: product flags are expansive pointwise. -/
theorem manyFlag_expansive_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (Q : Flag Time)
    (p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyLocatedSemilattice base hbase).le (p, t)
      ((manyFlag base hbase Q).toFun (p, t)) := by
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  exact (manyFlag base hbase Q).expansive (p, t)

/--
Definition 3.3.2: product flag application is consistent exactly when the base
flag application is consistent.
-/
theorem manyFlag_consistent_iff_base_consistent
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (Q : Flag Time)
    (p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyLocatedSemilattice base hbase).ConsistentTime
        ((manyFlag base hbase Q).toFun (p, t)) ↔
      ConsistentTime (Q t) := by
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  constructor
  · intro hprod htop
    have htopBase : Q t = top base := by
      simpa [hbase (Q t)] using htop
    exact hprod (Prod.ext rfl htopBase)
  · intro hbaseCons htopProd
    have htopBase : Q t = top base :=
      congrArg Prod.snd htopProd
    have htop : Q t = top (controller (Q t)) := by
      simpa [hbase (Q t)] using htopBase
    exact hbaseCons htop

theorem manyFlag_injective
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) {Q Q' : Flag Time}
    (h : manyFlag base hbase Q = manyFlag base hbase Q') : Q = Q' := by
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  have hfun : Q.toFun = Q'.toFun := by
    funext x
    have hp :=
      congrArg (fun F : @Flag (Nat × Time) Nat (manyLocatedSemilattice base hbase) =>
        F.toFun (0, x)) h
    exact congrArg Prod.snd hp
  cases Q
  cases Q'
  simpa using hfun

/-- Definition 3.3.2: lifted cutting flag-set. -/
def manyCuttingFlagSet
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) :
    @FlagSet (Nat × Time) Nat (manyLocatedSemilattice base hbase) :=
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  { member := fun Q => ∃ kind i, Q = manyFlag base hbase (cutting kind i)
    injective_where_consistent := by
      intro Q Q' t t' hmem hmem' hcons heq
      rcases hmem with ⟨kind, i, rfl⟩
      rcases hmem' with ⟨kind', j, rfl⟩
      cases t with
      | mk p x =>
        cases t' with
        | mk _p' x' =>
          dsimp [manyFlag] at heq hcons ⊢
          have hbaseCons : ConsistentTime ((cutting kind i) x) := by
            intro htop
            apply hcons
            dsimp [LocatedSemilattice.ConsistentTime, manyLocatedSemilattice]
            exact congrArg (fun y => (p, y))
              (by simpa [hbase ((cutting kind i) x)] using htop)
          have hbaseEq : (cutting kind i) x = (cutting kind' j) x' := by
            exact congrArg Prod.snd heq
          have hflag : cutting kind i = cutting kind' j :=
            cuttingFlagSet.injective_where_consistent
              (cutting_mem kind i) (cutting_mem kind' j) hbaseCons hbaseEq
          rw [hflag] }

/-- Definition 3.3.2: lifted cutting flags belong to the lifted cutting flag-set. -/
theorem manyCuttingFlagSet_member_manyFlag
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (kind : CutFlagKind) (i : Nat) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyCuttingFlagSet base hbase).member
      (manyFlag base hbase (cutting kind i)) :=
  ⟨kind, i, rfl⟩

/-- Lemma 3.3.3: the product construction `L_×` is a located semilattice with Cut. -/
def manyControllers
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) : LocatedSemilatticeWithCut (Nat × Time) Nat :=
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  { toLocatedSemilattice := manyLocatedSemilattice base hbase
    cuttingFlagSet := manyCuttingFlagSet base hbase
    cutting := fun kind i => manyFlag base hbase (cutting kind i)
    cutting_mem := by
      intro kind i
      exact ⟨kind, i, rfl⟩
    cutting_mem_complete := by
      intro Q hmem
      exact hmem
    next_le_cutme := by
      intro j t
      cases t with
      | mk p x =>
        constructor
        · rfl
        · exact congrArg (fun y => (p, y)) (next_le_cutme j x).2
    next_le_cutyou := by
      intro j t
      cases t with
      | mk p x =>
        constructor
        · rfl
        · exact congrArg (fun y => (p, y)) (next_le_cutyou j x).2
    cutyou_le_next := by
      intro i j hij t
      cases t with
      | mk p x =>
        constructor
        · rfl
        · exact congrArg (fun y => (p, y)) (cutyou_le_next hij x).2
    cutme_contradicts_cutyou := by
      intro j t t' hctrl
      cases t with
      | mk p x =>
        cases t' with
        | mk _p' x' =>
          constructor
          · exact hctrl
          · dsimp at hctrl ⊢
            cases hctrl
            have hcontr :=
              cutme_contradicts_cutyou j ((hbase x).trans (hbase x').symm)
            simpa [manyLocatedSemilattice, manyFlag,
              hbase ((cutting CutFlagKind.cutMe j) x)] using hcontr.2
    cutting_injective := by
      intro _kind _kind' _i _i' h
      exact cutting_injective (manyFlag_injective base hbase h) }

/-- Definition 3.3.2: product bottom in the final Cut package. -/
theorem manyControllers_bot_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) :
    (manyControllers base hbase).toLocatedSemilattice.bot p = (p, bot base) := by
  rfl

/-- Definition 3.3.2: product top in the final Cut package. -/
theorem manyControllers_top_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) :
    (manyControllers base hbase).toLocatedSemilattice.top p = (p, top base) := by
  rfl

/-- Definition 3.3.2: product attestation in the final Cut package. -/
theorem manyControllers_attest_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p p' : Nat) (t t' : Time) :
    (manyControllers base hbase).toLocatedSemilattice.attest (p, t) (p', t') =
      (p, t # t') := by
  rfl

/--
Definition 3.3.2: product controller projection in the
final Cut package.
-/
theorem manyControllers_controller_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (p : Nat) (t : Time) :
    (manyControllers base hbase).toLocatedSemilattice.controller (p, t) = p := by
  rfl

/--
Definition 3.3.2: in the final many-controller Cut package, each controller
fiber has the same order as the one-controller base model.
-/
theorem manyControllers_same_controller_le_iff_base_le
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyControllers base hbase).toLocatedSemilattice.le (p, t) (p, t') ↔ t ≼ t' := by
  exact manyLocatedSemilattice_same_controller_le_iff_base_le base hbase p t t'

/--
Definition 3.3.2: in the final many-controller Cut package, strict order in
each controller fiber is the base strict order.
-/
theorem manyControllers_same_controller_lt_iff_base_lt
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyControllers base hbase).toLocatedSemilattice.lt (p, t) (p, t') ↔ t ≺ t' := by
  exact manyLocatedSemilattice_same_controller_lt_iff_base_lt base hbase p t t'

/--
Definition 3.3.2: in the final many-controller Cut package, contradiction in
each controller fiber is exactly contradiction in the one-controller base
model.
-/
theorem manyControllers_same_controller_contradicts_iff_base_contradicts
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base) (p : Nat) (t t' : Time) :
    (manyControllers base hbase).toLocatedSemilattice.Contradicts (p, t) (p, t') ↔
      t 🗲 t' := by
  exact
    manyLocatedSemilattice_same_controller_contradicts_iff_base_contradicts
      base hbase p t t'

/-- Definition 3.3.2: product same-index `cutMe` and `cutYou` branches contradict. -/
theorem manyControllers_cutMe_contradicts_cutYou
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (j p : Nat) (t t' : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    (manyControllers base hbase).toLocatedSemilattice.Contradicts
      (((manyControllers base hbase).cutMe j).toFun (p, t))
      (((manyControllers base hbase).cutYou j).toFun (p, t')) := by
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  exact (manyControllers base hbase).cutme_contradicts_cutyou j rfl

/-- Sequentiality transfers to the many-controller located semilattice with Cut. -/
theorem manyControllers_sequential
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (hseq : Sequential (Time := Time)) :
    (manyControllers base hbase).toLocatedSemilattice.Sequential :=
  manyLocatedSemilattice_sequential base hbase hseq

/-- Lemma 3.3.3: multiplying the concrete one-controller model gives a sequential
many-controller located semilattice with Cut. -/
theorem manyController_sequential_locatedSemilatticeWithCut_exists :
    ∃ (Time Ctrl : Type), Nonempty (SequentialLocatedSemilatticeWithCut Time Ctrl) :=
  ⟨Nat × ConcreteTime, Nat,
    ⟨{ toLocatedSemilatticeWithCut :=
         manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit (by intro t; rfl)
       sequential :=
         manyControllers_sequential (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
           (by intro t; rfl) concreteLocatedSemilattice_sequential }⟩⟩

/-- Definition 3.3.2: product cutting-flag application. -/
theorem manyControllers_cutting_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (kind : CutFlagKind) (i p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    ((manyControllers base hbase).cutting kind i).toFun (p, t) =
      (p, cutting kind i t) :=
  rfl

/-- Definition 3.3.2: product `nextIndex` flag. -/
theorem manyControllers_nextIndex_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (i p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    ((manyControllers base hbase).nextIndex i).toFun (p, t) =
      (p, nextIndex i t) :=
  rfl

/-- Definition 3.3.2: product `cutMe` flag. -/
theorem manyControllers_cutMe_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (i p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    ((manyControllers base hbase).cutMe i).toFun (p, t) =
      (p, cutMe i t) :=
  rfl

/-- Definition 3.3.2: product `cutYou` flag. -/
theorem manyControllers_cutYou_apply
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (i p : Nat) (t : Time) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    ((manyControllers base hbase).cutYou i).toFun (p, t) =
      (p, cutYou i t) :=
  rfl

/--
If a base one-controller model has no nontrivial strict growth between two same
cutting-flag outputs, then its many-controller product has no such strict growth in any
fixed product controller fiber.
-/
theorem manyControllers_no_same_flag_strict_growth_of_base
    {Time : Type v} {Ctrl : Type u} [inst : LocatedSemilatticeWithCut Time Ctrl] (base : Ctrl)
    (hbase : ∀ t : Time, controller t = base)
    (kind : CutFlagKind) (i p : Nat) {t t' : Time}
    (hno : ¬ (cutting kind i t) ≺ (cutting kind i t')) :
    letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
    ¬ (manyControllers base hbase).toLocatedSemilattice.lt
      (((manyControllers base hbase).cutting kind i).toFun (p, t))
      (((manyControllers base hbase).cutting kind i).toFun (p, t')) := by
  letI : LocatedSemilattice (Nat × Time) Nat := manyLocatedSemilattice base hbase
  intro hlt
  rw [manyControllers_cutting_apply base hbase kind i p t,
    manyControllers_cutting_apply base hbase kind i p t'] at hlt
  exact hno
    ((manyLocatedSemilattice_same_controller_lt_iff_base_lt base hbase p
      (cutting kind i t) (cutting kind i t')).mp hlt)

/-- Located-semilattice instance on the many-controller product of the concrete
consistency model, local to the obstruction theorem below so the product flag
projections resolve. -/
local instance : LocatedSemilattice (Nat × ConcreteTime) Nat :=
  manyLocatedSemilattice (inst := concreteLocatedSemilatticeWithCut) PUnit.unit (by intro t; rfl)

/--
The many-controller product of the concrete consistency model inherits the one-controller
obstruction. It cannot supply nontrivial strict growth between consistent outputs of the
same cutting flag, so it cannot be an explicit inconsistent-index witness.
-/
theorem manyConcreteFlag_no_consistent_same_flag_strict_growth
    (kind : CutFlagKind) (i p : Nat)
    {t t' : ConcreteTime}
    (hcons :
      (manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
          (by intro t; rfl)).toLocatedSemilattice.ConsistentTime
        (((manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
            (by intro t; rfl)).cutting kind i).toFun (p, t)))
    (hcons' :
      (manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
          (by intro t; rfl)).toLocatedSemilattice.ConsistentTime
        (((manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
            (by intro t; rfl)).cutting kind i).toFun (p, t'))) :
    ¬ (manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
        (by intro t; rfl)).toLocatedSemilattice.lt
      (((manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
          (by intro t; rfl)).cutting kind i).toFun (p, t))
      (((manyControllers (inst := concreteLocatedSemilatticeWithCut) PUnit.unit
          (by intro t; rfl)).cutting kind i).toFun (p, t')) := by
  have hbase : ∀ s : ConcreteTime, controller s = PUnit.unit := by
    intro s
    rfl
  have hconsBase :
      ConsistentTime (concreteLocatedSemilatticeWithCut.cutting kind i t) :=
    (manyFlag_consistent_iff_base_consistent (inst := concreteLocatedSemilatticeWithCut)
      PUnit.unit hbase (concreteLocatedSemilatticeWithCut.cutting kind i) p t).mp hcons
  have hconsBase' :
      ConsistentTime (concreteLocatedSemilatticeWithCut.cutting kind i t') :=
    (manyFlag_consistent_iff_base_consistent (inst := concreteLocatedSemilatticeWithCut)
      PUnit.unit hbase (concreteLocatedSemilatticeWithCut.cutting kind i) p t').mp hcons'
  exact manyControllers_no_same_flag_strict_growth_of_base
    (inst := concreteLocatedSemilatticeWithCut) PUnit.unit hbase kind i p
    (concreteFlag_no_consistent_same_flag_strict_growth kind i hconsBase hconsBase')

end ConsistentHistories.Models.Cut.Consistency
